const String appbarTitle = 'BMI CALCULATOR';
const String calculateYourBMI = 'Calculate Your BMI';
const String male = 'MALE';
const String female = 'FEMALE';
const String strHeight = 'HEIGHT';
const String strUnit = 'cm';
const String strAge = 'AGE';
const String strWeight = 'WEIGHT';
const String strResult = 'Your Result';